# <img style="float: left; padding-right: 10px; width: 45px" src="iacs.png"> S-109A Introduction to Data Science 


# Do This Before Lab 0
(created along with Rahul Dave for cs109)

**Harvard University**<br>
**Summer 2018**<br>
**Instructors:** Pavlos Protopapas and Kevin Rader



## Using Jupyterhub

Until you install Anaconda on your machine (see below), and even afterwords to follow along in class, you might want to use Jupyterhub.

This is a service provided to us by SEAS. You can access it if you are a registered student, through the Canvas for this course, on the menu at the left:

![](images/canvas.png)

You can upload notebooks from places we will provide to this instance of jupyter; in the near future we will provide a way for you to copy and edit notebooks directly in Jupyterhub.

## Getting and installing Python

You will be using Python throughout the course, including many popular 3rd party Python libraries for scientific computing. [Anaconda](http://continuum.io/downloads) is an easy-to-install bundle of Python and most of these libraries. We **require**  that you use Anaconda for this course. 

For this course, we are using **Python 3**, not **Python 2**.

See: http://docs.continuum.io/anaconda/install

The **Jupyter** notebook (also called the **IPython** notebook) runs in the browser. For me, it works best in Google Chrome or Safari. You probably want to use one of these for the course assignments.

### Installing Anaconda

The Anaconda Python distribution is an easily-installable bundle of Python and many of the libraries used throughout this class. Unless you have a good reason not to, we recommend that you use Anaconda.

### Mac/Linux users

1. Download the [appropriate version](http://continuum.io/downloads) of Anaconda
1. Follow the instructions on that page to run the installer
1. Test out the IPython notebook: open a Terminal window, and type

`jupyter notebook`. 

Or use the Anaconda Launcher which might have been placed on your desktop. 

A new browser window should pop up. 

Click `New Notebook` to create a new notebook file. **Trick**: give this notebook a unique name by clicking on the word "Untitled" at the top, like `my-little-rose`. Use Spotlight (upper right corner of the mac desktop, looks like a maginifier) to search for this name. In this way, you will know which folder your notebook opens in by default.

You will have to occasionally work in the terminal on mac or linux. Mac users can access it (a terminal app is built into the mac) by typing "terminal" in spotlight or through Launchpad.

You might also want to choose a specific folder to work in, something like  `cs109a` under `Documents`. In this case, open the terminal, and do:

`cd Documents/cs109a`

and then type:

`jupyter notebook`

### Windows Users

1. Download the [appropriate version](http://continuum.io/downloads) of Anaconda
1. Follow the instructions on that page to run the installer. This will typically create a directory at `C:\Anaconda`
1. Test it out: start the Anaconda launcher, which you can find in `C:\Anaconda` or, in the Start menu. Start the IPython notebook. A new browser window should open. 
1. Click `New Notebook`, which should open a new page. **Trick**: give this notebook a unique name, like `my-little-rose`. Use Explorer (usually start menu on windows desktops) to search for this name. In this way, you will know which folder your notebook opens in by default.


Windows users should consider installing the program `git-bash`. It gives you a nice terminal to work with.

### All Users

If you did not add Anaconda to your path, be sure to use the full path to the python and ipython executables, such as `/anaconda/bin/python`.

If you already have installed Anaconda at some point in the past, you can easily update to the latest Anaconda version by updating conda, then Anaconda as follows:

```
conda update conda
conda update anaconda
```


## Hello, Jupyter

The Jupyter Notebook is a web application that allows you to create interactive documents that contain live code, equations, visualizations and explanatory text.

![](images/jupyterdemo.png)

When Jupyter app loads, you see a dashboard displaying files in the Jupyter home directory (you can reset this)

![](images/jupyterhome.png)

Each notebook consists of blocks of cells. Each cell can display rich text elements (Markdown) or code. Code is executed by a "computational engine" called the **kernel** . The output of the code is displayed directly below. 

![](images/jupyter.png)

Each cell can be executed independently, but once a block of code is executed, it lives in the memory of the kernel. 

![](images/cells.png)

You'll be using them to complete labs and homework. Once you've set up Python, please download this page, and open it with IPython by typing

```
jupyter notebook <name_of_downloaded_file>
```

As mentioned earlier in the Mac section, you can also open the notebook in any folder by `cd`ing to the folder in the terminal, and typing

```
jupyter notebook .
```

in that folder.

The anaconda install also probably dropped a launcher on your desktop. You can use the launcher, and select "jupyter notebook" from there. In this case you will need to find out which folder you are running in.

It loolks like this for me:

![jupyter](images/jupyter2.png)

Notice that you can use the user interface to create new folders and text files, and even open new terminals, all of which might come useful to you. To create a new notebook, you can use "Python 3" under notebooks. You may not have the other choices available (I have julia for example, which is another language that uses the same notebook interface).

For the rest of this setup test, use your local copy of this page, running on jupyter.

Notebooks are composed of many "cells", which can contain text (like this one), or code (like the one below). Double click on the cell below, and evaluate it by clicking the "play" button above, for by hitting shift + enter

In [1]:
x = [10, 20, 30, 40, 50]
for item in x:
    print("Item is ", item)

Item is  10
Item is  20
Item is  30
Item is  40
Item is  50


You must be careful to make sure you are running the Anaconda version of python, since those operating systems come preinstalled with their own versions of python.

This is how you can see the version in the jupyter interface

In [2]:
import sys
print(sys.version)

3.5.0 (default, Sep 13 2015, 23:30:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]


You could also open a terminal and just type

`python` 

or

`ipython`

there. When the program starts up, you should see "Anaconda" printed out, similar to the above. If this is the case, your install went well, and you can quit the python "interpreter" by typing Ctrl-D.


If you've successfully completed the above install, skip to below the troubleshooting section. All of the statements there should run.

## Troubleshooting

**PROBLEM**
You are using a Mac or Linux computer. When you start python at the terminal or do `sys.version` in the notebook, you don't see a line like `3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) `.

**Reason**
You are most likely running a different version of Python, and need to modify your Path (the list of directories your computer looks through to find programs). 

**Solution**
Find a file like `.bash_profile`, `.bashrc`, or `.profile`. Open the file in a text editor, and add a line at this line at the end: 

`export PATH="$HOME/anaconda/bin:$PATH"`. 

Close the file, open a new terminal window, type `source ~/.profile` (or whatever file you just edited). Type 

`which python`

-- you should see a path that points to the anaconda directory. If so, running `python` should load the proper version.

If this doesn't work (typing `which python` doesn't point to anaconda), you might be using a different shell. 

Type `echo $SHELL`. 

If this isn't `bash`, you need to edit a different startup file (for example, if `echo $SHELL` gives `$csh`, you need to edit your `.cshrc` file. The syntax for this file is slightly different: 

`set PATH = ($HOME/anaconda/bin $PATH)`

---

**PROBLEM**
You are running the right version of python (see above item), but are unable to import numpy. 

**Reason**
You are probably loading a different copy of numpy that is incompatible with Anaconda.

**Solution**
See the above item to find your `.bash_profile`, `.profile`, or `.bashrc` file. Open it, and add the line `unset PYTHONPATH` at the end. Close the file, open a new terminal window, type `source ~/.profile` (or whatever file you just edited), and try again.

---

**PROBLEM**
Under Windows, you receive an error message similar to the following: "'pip' is not recognized as an internal or external command, operable program or batch file."

**Reason**
The correct Anaconda paths might not be present in your PATH variable, or Anaconda might not have installed correctly.

**Solution**
Ensure the Anaconda directories to your path environment variable ("\Anaconda" and "\Anaconda\Scripts").  See [this page](http://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them) for details.

If this does not correct the problem, re-install Anaconda.


**IF YOU ARE STILL HAVING ISSUES ON THE INSTALL, POST TO PIAZZA. YOU'LL FIND HELP THERE. OR ASK IN YOUR SECTION**

## Python Libraries

### Testing latest libraries

In [3]:
#IPython is what you are using now to run the notebook
import IPython
print("IPython version:      %6.6s (need at least 5.0.0)" % IPython.__version__)

# Numpy is a library for working with Arrays
import numpy as np
print("Numpy version:        %6.6s (need at least 1.12.0)" % np.__version__)

# SciPy implements many different numerical algorithms
import scipy as sp
print("SciPy version:        %6.6s (need at least 0.19.0)" % sp.__version__)

# Pandas makes working with data tables easier
import pandas as pd
print("Pandas version:       %6.6s (need at least 0.20.0)" % pd.__version__)

# Module for plotting
import matplotlib
print("Matplotlib version:    %6.6s (need at least 2.0.0)" % matplotlib.__version__)

# SciKit Learn implements several Machine Learning algorithms
import sklearn
print("Scikit-Learn version: %6.6s (need at least 0.18.1)" % sklearn.__version__)

# Requests is a library for getting data from the Web
import requests
print("requests version:     %6.6s (need at least 2.9.0)" % requests.__version__)

#BeautifulSoup is a library to parse HTML and XML documents
import bs4
print("BeautifulSoup version:%6.6s (need at least 4.4)" % bs4.__version__)

import seaborn
print("Seaborn version:%6.6s (need at least 0.7)" % seaborn.__version__)

IPython version:       4.0.0 (need at least 5.0.0)
Numpy version:        1.11.0 (need at least 1.12.0)
SciPy version:        0.16.0 (need at least 0.19.0)
Pandas version:       0.16.2 (need at least 0.20.0)
Matplotlib version:     1.4.3 (need at least 2.0.0)
Scikit-Learn version: 0.16.1 (need at least 0.18.1)
requests version:      2.7.0 (need at least 2.9.0)


ImportError: No module named 'bs4'

If any of these libraries are missing or out of date, you will need to install them and restart jupyter.

## Kicking the tires

Lets try some things, starting from very simple, to more complex.

### Hello World

The following is the incantation we like to put at the beginning of every notebook. It loads most of the stuff we will regularly use.

In [ ]:
# The %... is an iPython thing, and is not part of the Python language.
# In this case we're just telling the plotting library to draw things on
# the notebook, instead of on a separate window.
%matplotlib inline 
#this line above prepares the jupyter notebook for working with matplotlib

# See all the "as ..." contructs? They're just aliasing the package names.
# That way we can call methods like plt.plot() instead of matplotlib.pyplot.plot().
# notice we use short aliases here, and these are conventional in the python community

import numpy as np # imports a fast numerical programming library
import scipy as sp #imports stats functions, amongst other things
import matplotlib as mpl # this actually imports matplotlib
import matplotlib.cm as cm # allows us easy access to colormaps
import matplotlib.pyplot as plt # sets up plotting under plt
import pandas as pd #lets us handle data as dataframes
# sets up pandas table display
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns #sets up styles and gives us more plotting options

### Hello matplotlib

The notebook integrates nicely with Matplotlib, the primary plotting package for python. This should embed a figure of a sine wave:

In [ ]:
x = np.linspace(0, 10, 30)  #array of 30 points from 0 to 10
y = np.sin(x)
z = y + np.random.normal(size=30) * .2
plt.plot(x, y, 'o-', label='A sine wave')
plt.plot(x, z, '-', label='Noisy sine')
plt.legend(loc = 'lower right')
plt.xlabel("X axis")
plt.ylabel("Y axis")           

TODO: should random seeds be added in here?

### Hello Numpy

The Numpy array processing library is the basis of nearly all numerical computing in Python. Here's a 30 second crash course. For more details, consult the [Numpy User's Guide](http://docs.scipy.org/doc/numpy-dev/user/index.html)

In [4]:
print("Make a 3 row x 4 column array of random numbers")
x = np.random.random((3, 4))
print(x,"\n")


print("Add 1 to every element")
x = x + 1
print(x,"\n")

print("Get the element at row 1, column 2")
print(x[1, 2])

# The colon syntax is called "slicing" the array. 
print("Get the first row")
print(x[0, :])

print("Last 2 items in the first row")
print(x[0, -2:])

print("Get every 2nd item in the first row")
print(x[0, ::2])

Make a 3 row x 4 column array of random numbers
[[ 0.05957479  0.56289064  0.07403221  0.56553381]
 [ 0.25538582  0.04039628  0.24521581  0.07849142]
 [ 0.48156524  0.46776524  0.13222912  0.05633539]] 

Add 1 to every element
[[ 1.05957479  1.56289064  1.07403221  1.56553381]
 [ 1.25538582  1.04039628  1.24521581  1.07849142]
 [ 1.48156524  1.46776524  1.13222912  1.05633539]] 

Get the element at row 1, column 2
1.24521580663
Get the first row
[ 1.05957479  1.56289064  1.07403221  1.56553381]
Last 2 items in the first row
[ 1.07403221  1.56553381]
Get every 2nd item in the first row
[ 1.05957479  1.07403221]


Print the maximum, minimum, and mean of the array. This does **not** require writing a loop. In the code cell below, type `x.m<TAB>`, to find built-in operations for common array statistics like this

In [5]:
print("Max is  ", x.max())
print("Min is  ", x.min())
print("Mean is ", x.mean())

Max is   1.56553381329
Min is   1.04039628242
Mean is  1.25161798038


Call the `x.max` function again, but use the `axis` keyword to print the maximum of each row in x.

In [6]:
print(x.max(axis=1))

[ 1.56553381  1.25538582  1.48156524]


Here's a way to quickly simulate 500 coin "fair" coin tosses (where the probabily of getting Heads is 50%, or 0.5)

In [7]:
x = np.random.binomial(500, .5)
print("number of heads:", x)

number of heads: 247


Repeat this simulation 500 times, and use the [plt.hist() function](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.hist) to plot a histogram of the number of Heads (1s) in each simulation

In [8]:
# 3 ways to run the simulations

# loop
heads = []
for i in range(500):
    heads.append(np.random.binomial(500, .5))

# "list comprehension"
heads = [np.random.binomial(500, .5) for i in range(500)]

# pure numpy, preferred
heads = np.random.binomial(500, .5, size=500)

histogram = plt.hist(heads, bins=10)

NameError: name 'plt' is not defined

In [9]:
heads.shape

(500,)